stages:
  my-conda-command:
    cmd: >
      calkit runenv -n conda --
      which python > results/conda.txt
    outs:
      - results/conda.txt:
          cache: false
  my-pixi-command:
    cmd: >
      calkit runenv -n main --
      which python > results/pixi.txt
    outs:
      - results/pixi.txt:
          cache: false
  my-docker-command:
    cmd: >
      calkit runenv -n ubuntu --
      cat /etc/lsb-release > results/ubuntu.txt
    outs:
      - results/ubuntu.txt:
          cache: false
