stages:
  my-conda-command:
    cmd: >
      calkit runenv -n conda --
      which python > results/conda.txt
    deps:
      - environment.yml
    outs:
      - results/conda.txt:
          cache: false
  my-pixi-command:
    cmd: >
      calkit runenv -n main --
      which python > results/pixi.txt
    deps:
      - pixi.toml
    outs:
      - results/pixi.txt:
          cache: false
  my-docker-command:
    cmd: >
      calkit runenv -n ubuntu --
      cat /etc/lsb-release > results/ubuntu.txt
    outs:
      - results/ubuntu.txt:
          cache: false
  my-uv-command:
    cmd: >
      calkit runenv -n my-uv --
      which python > results/uv.txt
    deps:
      - pyproject.toml
    outs:
      - results/uv.txt:
          cache: false
  my-uv-venv-command:
    cmd: >
      calkit runenv -n uv-venv --
      which python > results/uv-venv.txt
    deps:
      - requirements.txt
    outs:
      - results/uv-venv.txt:
          cache: false
  my-pixi-env-command:
    cmd: >
      calkit runenv -n pixi2 --
      python -c "import plotly; print(plotly.__file__)" > results/pixi2.txt
    deps:
      - pixi.toml
    outs:
      - results/pixi2.txt:
          cache: false
  my-openfoam-command:
    cmd: >
      calkit runenv -n openfoam --check --
      icoFoam -help > results/openfoam.txt
    deps:
      - Dockerfile
    outs:
      - results/openfoam.txt:
          cache: false
