[project]
name = "calkit-multienv-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "calkit-python>=0.8.5",
    "ipython>=8.30.0",
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
]
